name: Build .nuxt files
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install --network-concurrency 1
      - name: Build
        run: |
          yarn build
      - name: Upload artifacts (.nuxt)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: .nuxt
          path: ./.nuxt
          retention-days: 0
      - name: Remove node_modules
        run: |
          rm -rf node_modules
      - name: Upload artifacts (*)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: workspace
          path: ./
          retention-days: 0
